### ISSUE TITLE
Can't edit Performance

### ISSUE THREAD

**Issue by TomLomas** [IUrreta/DatabaseEditor#240]
When I make any changes in performance, I am then unable to save the changes, clicking the button doesn't do anything, then breaks the entire tool when trying to load anything else.

**Comment by IUrreta** [comment]
Can you show me your log.txt?

**Comment by TomLomas** [comment]
Log.txt pasted below.


2024-07-24 09:11:28,555 INFO: Command executed: {'command': 'connect'}
2024-07-24 09:11:32,930 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 09:41:25,420 INFO: Command executed: {'command': 'configUpdate', 'save': 'save0', 'alphatauri': 'visarb', 'alpine': 'alpine', 'alfa': 'stake', 'state': 'changed', 'icon': '../assets/custom/Logo.png', 'primaryColor': '#0d0d0d', 'secondaryColor': '#e6a800'}
2024-07-24 09:44:35,927 INFO: Command executed: {'command': 'configUpdate', 'save': 'save0', 'alphatauri': 'visarb', 'alpine': 'alpine', 'alfa': 'stake', 'state': 'changed', 'icon': '../assets/custom/Logo White.png', 'primaryColor': '#0d0d0d', 'secondaryColor': '#e6a800'}
2024-07-24 09:44:49,188 INFO: Command executed: {'command': 'teamRequest', 'teamID': '32'}
2024-07-24 09:45:09,476 INFO: Command executed: {'command': 'yearSelectedPrediction', 'year': '2024'}
2024-07-24 09:45:10,822 ERROR: Exception occurred while handling client message
Traceback (most recent call last):
  File "C:\Users\Tomlo\Desktop\Desktop\Games Customisation\F1M Customisation\DatabaseEditor\back\back.py", line 33, in handle_client
    await app_state.new_handler(data, client)
  File "C:\Users\Tomlo\Desktop\Desktop\Games Customisation\F1M Customisation\DatabaseEditor\back\back.py", line 19, in new_handler
    await command.execute()
  File "C:\Users\Tomlo\Desktop\Desktop\Games Customisation\F1M Customisation\DatabaseEditor\back\commands\predict.py", line 11, in execute
    prediction = predictor.predict(self.message["race"], self.message["year"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tomlo\Desktop\Desktop\Games Customisation\F1M Customisation\DatabaseEditor\back\scripts\predictor.py", line 210, in predict
    model = pickle.load(open("./models/PD03LR.pkl", "rb"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sklearn'
2024-07-24 09:46:14,548 INFO: Command executed: {'command': 'connect'}
2024-07-24 09:46:23,216 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 09:46:23,752 INFO: Command executed: {'command': 'yearSelected', 'year': '2024'}
2024-07-24 09:46:43,343 INFO: Command executed: {'command': 'requestDriver', 'driverID': '22', 'driver': 'Stoffel\nVANDOORNE'}
2024-07-24 09:46:49,954 INFO: Command executed: {'command': 'swap', 'driver1ID': '13', 'driver2ID': '3', 'driver1': 'Daniel\nRICCIARDO', 'driver2': 'Alexander\nALBON'}
2024-07-24 09:46:51,255 INFO: Command executed: {'command': 'swap', 'driver1ID': '13', 'driver2ID': '3', 'driver1': 'Daniel\nRICCIARDO', 'driver2': 'Alexander\nALBON'}
2024-07-24 09:48:28,759 INFO: Command executed: {'command': 'calendar', 'calendarCodes': '212102 120000 1703100 302110 2510100 1421200 602100 700100 500100 912210 1012000 1211100 1324300 2301200 421100 1510000 1901210 1822300 2011110 2601210'}
2024-07-24 09:48:32,627 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 09:48:40,650 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '3'}
2024-07-24 09:48:43,663 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 09:49:31,668 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '3'}
2024-07-24 09:49:34,320 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 09:57:03,565 INFO: Command executed: {'command': 'connect'}
2024-07-24 10:01:36,050 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 10:02:13,881 INFO: Command executed: {'command': 'editStats', 'driverID': '22', 'driver': 'Stoffel  VANDOORNE', 'statsArray': '82 79 81 73 88 80 82 78 84 44 49', 'typeStaff': '0', 'retirement': '40', 'driverNum': '5', 'wants1': 1, 'mentality': '1 1 1 ', 'superLicense': 1, 'marketability': '75'}
2024-07-24 10:02:45,543 INFO: Command executed: {'command': 'editStats', 'driverID': '74', 'driver': 'Mick  SCHUMACHER', 'statsArray': '80 77 81 74 79 77 77 85 81 55 48', 'typeStaff': '0', 'retirement': '40', 'driverNum': '47', 'wants1': 1, 'mentality': '1 1 1 ', 'superLicense': 1, 'marketability': '80'}
2024-07-24 10:02:53,126 INFO: Command executed: {'command': 'teamRequest', 'teamID': '32'}
2024-07-24 10:03:44,305 INFO: Command executed: {'command': 'editTeam', 'teamID': '32', 'facilities': [['32', 0.99], ['22', 0.99], ['52', 0.99], ['62', 0.99], ['72', 0.99], ['82', 0.99], ['151', 1], ['132', 0.98], ['12', 0.98], ['101', 1], ['111', 1], ['121', 1], ['92', 1], ['142', 1], ['42', 0.98]], 'seasonObj': '7', 'longTermObj': '2', 'longTermYear': '2026', 'teamBudget': '57887087', 'costCapEdit': 0, 'confidence': '44', 'pitCrew': {'32': '75', '34': '75', '35': '75', '36': '70', '38': 0, '39': '75', '40': '75', '41': '75', '42': '75'}, 'engine': '7', 'teamName': 'Lomas GP'}
2024-07-24 10:03:52,575 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 10:03:57,797 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 15:27:35,585 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:15:53,505 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 16:15:57,956 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:16:23,347 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:16:29,755 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 16:16:37,683 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:17:19,942 INFO: Command executed: {'command': 'editEngine', 'engines': {'1': {'6': '75.0', '10': '95.0', '11': '80.0', '12': '77.5', '14': '68.0', '18': '57.0', '19': '50.0'}, '4': {'6': '65.0', '10': '100.0', '11': '85.0', '12': '70.0', '14': '60.0', '18': '50.0', '19': '62.0'}, '7': {'6': '100.00', '10': '100.00', '11': '65.0', '12': '82.8', '14': '100.00', '18': '100.00', '19': '100.00'}, '10': {'6': '100.0', '10': '80.0', '11': '75.0', '12': '85.0', '14': '73.0', '18': '62.0', '19': '55.0'}}}
2024-07-24 16:17:41,882 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '10'}
2024-07-24 16:17:43,859 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:17:45,820 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '8'}
2024-07-24 16:17:59,511 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:21:40,296 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:21:56,366 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 16:22:01,626 INFO: Command executed: {'command': 'teamRequest', 'teamID': '32'}
2024-07-24 16:22:06,961 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:22:54,898 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:23:08,054 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 16:23:09,304 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:24:23,782 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:24:59,180 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 16:25:25,219 INFO: Command executed: {'command': 'configUpdate', 'save': 'save0', 'alphatauri': 'visarb', 'alpine': 'alpine', 'alfa': 'stake', 'state': 'changed', 'icon': '../assets/custom/Logo White.png', 'primaryColor': '#ffb600', 'secondaryColor': '#ffffff'}
2024-07-24 16:25:32,865 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '5'}
2024-07-24 16:25:34,298 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:27:57,369 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}
2024-07-24 16:28:32,838 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:33:24,444 INFO: Command executed: {'command': 'connect'}
2024-07-24 16:33:35,763 INFO: Command executed: {'command': 'saveSelected', 'save': 'save0.sav'}
2024-07-24 16:33:46,896 INFO: Command executed: {'command': 'teamRequest', 'teamID': '32'}
2024-07-24 16:34:16,083 INFO: Command executed: {'command': 'editEngine', 'engines': {'1': {'6': '75.0', '10': '95.0', '11': '80.0', '12': '77.5', '14': '68.0', '18': '57.0', '19': '50.0'}, '4': {'6': '65.0', '10': '100.0', '11': '85.0', '12': '70.0', '14': '60.0', '18': '50.0', '19': '62.0'}, '7': {'6': '100.00', '10': '100.00', '11': '65.0', '12': '82.8', '14': '100.00', '18': '100.00', '19': '100.00'}, '10': {'6': '100.0', '10': '80.0', '11': '75.0', '12': '85.0', '14': '73.0', '18': '62.0', '19': '55.0'}}}
2024-07-24 16:34:21,381 INFO: Command executed: {'command': 'teamRequest', 'teamID': '8'}
2024-07-24 16:34:22,961 INFO: Command executed: {'command': 'teamRequest', 'teamID': '32'}
2024-07-24 16:34:44,361 INFO: Command executed: {'command': 'editTeam', 'teamID': '32', 'facilities': [['32', 0.92], ['22', 0.91], ['52', 0.9], ['62', 0.91], ['72', 0.92], ['82', 0.92], ['151', 0.85], ['132', 0.88], ['12', 0.88], ['101', 0.82], ['111', 0.87], ['121', 0.87], ['92', 0.9], ['142', 1], ['42', 0.88]], 'seasonObj': '7', 'longTermObj': '2', 'longTermYear': '2026', 'teamBudget': '50803389', 'costCapEdit': 113000000, 'confidence': '18', 'pitCrew': {'32': '80', '34': '75', '35': '80', '36': '71', '38': 0, '39': '78', '40': '80', '41': '80', '42': '80'}, 'engine': '7', 'teamName': 'Lomas GP'}
2024-07-24 16:34:51,943 INFO: Command executed: {'command': 'editTeam', 'teamID': '32', 'facilities': [['32', 0.92], ['22', 0.91], ['52', 0.9], ['62', 0.91], ['72', 0.92], ['82', 0.92], ['151', 0.85], ['132', 0.88], ['12', 0.88], ['101', 0.82], ['111', 0.87], ['121', 0.87], ['92', 0.9], ['142', 1], ['42', 0.88]], 'seasonObj': '9', 'longTermObj': '2', 'longTermYear': '2026', 'teamBudget': '50803389', 'costCapEdit': 113000000, 'confidence': '18', 'pitCrew': {'32': '80', '34': '75', '35': '80', '36': '71', '38': 0, '39': '78', '40': '80', '41': '80', '42': '80'}, 'engine': '7', 'teamName': 'Lomas GP'}
2024-07-24 16:35:33,273 INFO: Command executed: {'command': 'editStats', 'driverID': '22', 'driver': 'Stoffel  VANDOORNE', 'statsArray': '83 79 81 73 88 80 82 78 84 44 49', 'typeStaff': '0', 'retirement': '40', 'driverNum': '5', 'wants1': 1, 'mentality': '1 1 1 ', 'superLicense': 1, 'marketability': '75'}
2024-07-24 16:35:46,326 INFO: Command executed: {'command': 'editStats', 'driverID': '74', 'driver': 'Mick  SCHUMACHER', 'statsArray': '80 77 81 74 79 77 77 86 81 55 48', 'typeStaff': '0', 'retirement': '40', 'driverNum': '47', 'wants1': 1, 'mentality': '1 1 1 ', 'superLicense': 1, 'marketability': '80'}
2024-07-24 16:36:17,324 INFO: Command executed: {'command': 'editStats', 'driverID': '159', 'driver': 'Pau  RIVERA', 'statsArray': '100 100 84', 'typeStaff': '2', 'retirement': '60', 'driverNum': 'undefined', 'wants1': 1, 'mentality': '1 1 1 ', 'superLicense': 0, 'marketability': '80'}
2024-07-24 16:36:31,717 INFO: Command executed: {'command': 'editStats', 'driverID': '149', 'driver': 'Mathew  OGLE', 'statsArray': '100 100 80', 'typeStaff': '2', 'retirement': '62', 'driverNum': 'undefined', 'wants1': 1, 'mentality': '1 1 1 ', 'superLicense': 0, 'marketability': '80'}
2024-07-24 21:13:17,420 INFO: Command executed: {'command': 'performanceRequest', 'teamID': '32'}

**Comment by IUrreta** [comment]
Strange because I don't see any error

**Comment by OrangeGuy149** [comment]
Try finishing the first race of the season, then after that it worked for me.

**Comment by miniman1706** [comment]
The same thing happened to me, was this a my team career?

**Comment by IUrreta** [comment]
This issue should be gone with the new online version. Check https://www.f1dbeditor.com/
