### ISSUE TITLE
Kick Sauber Team update causing error

### ISSUE THREAD

**Issue by bikeracer4487** [IUrreta/DatabaseEditor#243]
When I attempt to modify values on the Kick Sauber team page, when I click 'Save' I get an error message saying "Something went wrong. Please restart the tool." with the following Traceback in the terminal:

Traceback (most recent call last):
  File "C:\Users\Doug\Documents\GitHub\DatabaseEditor\back\back.py", line 34, in handle_client
    await app_state.new_handler(data, client)
  File "C:\Users\Doug\Documents\GitHub\DatabaseEditor\back\back.py", line 21, in new_handler
    await command.execute()
  File "C:\Users\Doug\Documents\GitHub\DatabaseEditor\back\commands\editTeam.py", line 14, in execute
    info = [f"Succesfully edited {self.team_replace_dict[self.message['teamName']]}'s details"]
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Stake Sauber'


I thought editing "Alfa Romeo" to "Stake Sauber" in teamDict in the editTeam.py file would fix the issue, but it causes the same error message.

**Comment by IUrreta** [comment]
Please send me your save so I can take a look

**Comment by IUrreta** [comment]
Don't worry, I found the bug, will be solved in the next patch
