### ISSUE TITLE
Can't transfer drivers

### ISSUE THREAD

**Issue by russonauta** [IUrreta/DatabaseEditor#244]
I created a new F1 Manager 24 My Team save and, right after the sponsors agreement, saved it and tried to load it on the app to make driver transfers, since I selected Hulkemberg to my team on the game, Haas hires Cordeel and I want to swich him for Bearman but I keep getting the "Something went wrong" error...

This is the save (directly from the game, before the app changes): https://drive.google.com/file/d/1GJSASL-Es1PnUctdTC3RqmHosPn8p9OJ/view?usp=sharing

The log.txt shows 
2024-07-24 17:36:49,122 INFO: Command executed: {'command': 'connect'}
2024-07-24 17:37:31,037 INFO: Command executed: {'command': 'saveSelected', 'save': 'save1.sav'}
2024-07-24 17:37:34,823 INFO: Command executed: {'command': 'configUpdate', 'save': 'save1', 'alphatauri': 'visarb', 'alpine': 'alpine', 'alfa': 'stake', 'state': 'neverask'}
2024-07-24 17:37:46,606 ERROR: Exception occurred while handling client message
Traceback (most recent call last):
  File "C:\Users\*\Documents\F1 Manager 23 Database Editor\DatabaseEditor\back\back.py", line 33, in handle_client
    await app_state.new_handler(data, client)
  File "C:\Users\*\Documents\F1 Manager 23 Database Editor\DatabaseEditor\back\back.py", line 19, in new_handler
    await command.execute()
  File "C:\Users\*\Documents\F1 Manager 23 Database Editor\DatabaseEditor\back\commands\swap.py", line 13, in execute
    run_trasnsfer(argument)
  File "C:\Users\*\Documents\F1 Manager 23 Database Editor\DatabaseEditor\back\scripts\transfer_driver_23.py", line 229, in run_script
    cursor.execute(f"UPDATE Staff_RaceEngineerDriverAssignments SET IsCurrentAssignment = 0 WHERE RaceEngineerID = {engineer_2_id[0]} AND DriverID = {driver_2_id[0]}")
                                                                                                                    ~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by IUrreta** [comment]
Brother I don't have access to the file

**Comment by russonauta** [comment]
Sorry, you should have access now:
https://drive.google.com/file/d/1GJSASL-Es1PnUctdTC3RqmHosPn8p9OJ/view?usp=sharing

**Comment by IUrreta** [comment]
Found the error. For some reason haas has not asigned a race engineer to cordeel, and that is causing the crash when trying to do the trasnfers. Tomorrow I'll release a new version fixing multiplem bugs, so I'll see how to fix this one before that

**Comment by russonauta** [comment]
All good! I can wait for tomorrow if you're not already into this.

**Comment by IUrreta** [comment]
Should be fixed now

**Comment by russonauta** [comment]
Gracias!
