### ISSUE TITLE
Data Base disconnects when I add the save

### ISSUE THREAD

**Issue by Lucas1134F** [IUrreta/DatabaseEditor#327]
![Captura de tela 2024-08-03 160118](https://github.com/user-attachments/assets/0e12bc2f-8ccf-41b2-91a0-ed8d1c802a50)

**Comment by jameswolf1423** [comment]
I have the same problem

**Comment by zeinalfa708** [comment]
same

Traceback (most recent call last):
  File "Z:\aplikasi\DatabaseEditor-2.2.0\back\back.py", line 34, in handle_client
    await app_state.new_handler(data, client)
  File "Z:\aplikasi\DatabaseEditor-2.2.0\back\back.py", line 21, in new_handler
    await command.execute()
  File "Z:\aplikasi\DatabaseEditor-2.2.0\back\commands\saveSelected.py", line 67, in execute
    cars = car_analysis.get_performance_all_cars(game_year[2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\aplikasi\DatabaseEditor-2.2.0\back\scripts\car_analysis.py", line 264, in get_performance_all_cars
    driver_number = self.get_driver_number_with_car(team, car)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\aplikasi\DatabaseEditor-2.2.0\back\scripts\car_analysis.py", line 291, in get_driver_number_with_car
    driver_id = self.cursor.execute(f"SELECT con.StaffID FROM Staff_Contracts con JOIN Staff_GameData gam ON con.StaffID = gam.StaffID WHERE con.TeamID = {team_id} AND gam.StaffType = 0 AND con.ContractType = 0 AND con.PosInTeam = {car_id}").fetchone()[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable


i found this, IDK. Developer please FIX

**Comment by zeinalfa708** [comment]
Anyway, It should me labeled BUG instead of enchantment
