### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TaneSerin** [IUrreta/DatabaseEditor#351]
**Describe the bug**
I have been disconected when i want to change performance settings

**To Reproduce**
1. Select file..'
2. Click on my team
3. Change parameters of any of parts of the car
4. Have been disconected

Traceback (most recent call last):
  File "C:\Users\amd19\OneDrive\Escritorio\DatabaseEditor-2.2.2\back\back.py", line 34, in handle_client
    await app_state.new_handler(data, client)
  File "C:\Users\amd19\OneDrive\Escritorio\DatabaseEditor-2.2.2\back\back.py", line 21, in new_handler
    await command.execute()
  File "C:\Users\amd19\OneDrive\Escritorio\DatabaseEditor-2.2.2\back\commands\editPerformance.py", line 14, in execute
    car_analysis.fit_loadouts_dict(self.message['loadouts'], self.message['teamID'])
  File "C:\Users\amd19\OneDrive\Escritorio\DatabaseEditor-2.2.2\back\scripts\car_analysis.py", line 403, in fit_loadouts_dict
    items_2 = self.cursor.execute(f"SELECT ItemID FROM Parts_Items WHERE DesignID = {design_2} AND BuildWork = {standard_buildwork_per_part[int(part)]} AND AssociatedCar IS NULL").fetchall()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: None

**Comment by IUrreta** [comment]
This should be fixed in the next update. Sorry, I was on vacation :)
