### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vasco2OO4** [IUrreta/DatabaseEditor#400]
Can't get the editor to work.
when I run "run.bat" cmd shows the following:

"Version: 2.3.3
Virtual enviorment found.
Installing requirements...
Collecting websockets==12.0 (from -r requirements.txt (line 1))
  Using cached websockets-12.0-py3-none-any.whl.metadata (6.6 kB)
Collecting scikit-learn==1.3.2 (from -r requirements.txt (line 2))
  Using cached scikit-learn-1.3.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "C:\Users\vasco\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\vasco\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vasco\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\vasco\AppData\Local\Temp\pip-build-env-zd_f6ke2\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\vasco\AppData\Local\Temp\pip-build-env-zd_f6ke2\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vasco\AppData\Local\Temp\pip-build-env-zd_f6ke2\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 633, in <module>
        File "<string>", line 627, in setup_package
        File "<string>", line 554, in configure_extension_modules
        File "C:\Users\vasco\AppData\Local\Temp\pip-install-vjo__z4u\scikit-learn_4d533b1fc061467ab71f1113b1ab0246\sklearn\_build_utils\__init__.py", line 46, in cythonize_extensions
          basic_check_build()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\vasco\AppData\Local\Temp\pip-install-vjo__z4u\scikit-learn_4d533b1fc061467ab71f1113b1ab0246\sklearn\_build_utils\pre_build_helpers.py", line 73, in basic_check_build
          compile_test_program(code)
          ~~~~~~~~~~~~~~~~~~~~^^^^^^
        File "C:\Users\vasco\AppData\Local\Temp\pip-install-vjo__z4u\scikit-learn_4d533b1fc061467ab71f1113b1ab0246\sklearn\_build_utils\pre_build_helpers.py", line 31, in compile_test_program
          ccompiler.compile(
          ~~~~~~~~~~~~~~~~~^
              ["test_program.c"], output_dir="objects", extra_postargs=extra_postargs
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vasco\AppData\Local\Temp\pip-build-env-zd_f6ke2\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 379, in compile
          self.initialize()
          ~~~~~~~~~~~~~~~^^
        File "C:\Users\vasco\AppData\Local\Temp\pip-build-env-zd_f6ke2\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 289, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\vasco\AppData\Local\Temp\pip-build-env-zd_f6ke2\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 150, in _get_vc_env
          raise DistutilsPlatformError(
          ...<3 lines>...
          )
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

up to date in 583ms

21 packages are looking for funding
  run `npm fund` for details

> Database Editor F1 Manager@2.3.3 start
> electron .


connection handler failed
Traceback (most recent call last):
  File "C:\Users\vasco\AppData\Local\Programs\Python\Python313\Lib\site-packages\websockets\asyncio\server.py", line 373, in conn_handler
    await self.handler(connection)
          ~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: start_server.<locals>.<lambda>() missing 1 required positional argument: 'path'"

How can I solve the problem?
Thanks for the help.

**Comment by Vasco2OO4** [comment]
Had to downgrade python to version 3.11 and it worked
